name:                tessoku-book
version:             0.4.1.1
github:              "nobsun/tessoku-book"
license:             BSD3
author:              "Nobuo Yamashita"
maintainer:          "nobsun@sampou.org"
copyright:           "Copyright: (c) 2022 Nobuo Yamashita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/tessoku-book#readme>

dependencies:
- base >= 4.7 && < 5
- unicode-show
- bytestring
- utf8-string
- time
- hspec
- array
- containers

library:
  source-dirs: src

executables:
  tessoku-book:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    # - -threaded
    # - -with-rtsopts=-N
    dependencies:
    - tessoku-book
  
  A01:
    main:                Main.hs
    source-dirs:         app/a01
    ghc-options:
    - -rtsopts

  B01:
    main:                Main.hs
    source-dirs:         app/b01
    ghc-options:
    - -rtsopts
  
  A02:
    main:                Main.hs
    source-dirs:         app/a02
    ghc-options:
    - -rtsopts

  B02:
    main:                Main.hs
    source-dirs:         app/b02
    ghc-options:
    - -rtsopts

  A03:
    main:                Main.hs
    source-dirs:         app/a03
    ghc-options:
    - -rtsopts

  B03:
    main:                Main.hs
    source-dirs:         app/b03
    ghc-options:
    - -rtsopts

  A04:
    main:                Main.hs
    source-dirs:         app/a04
    ghc-options:
    - -rtsopts

  B04:
    main:                Main.hs
    source-dirs:         app/b04
    ghc-options:
    - -rtsopts

  A05:
    main:                Main.hs
    source-dirs:         app/a05
    ghc-options:
    - -rtsopts

  A06:
    main:                Main.hs
    source-dirs:         app/a06
    ghc-options:
    - -rtsopts

  B06:
    main:                Main.hs
    source-dirs:         app/b06
    ghc-options:
    - -rtsopts

  A07:
    main:                Main.hs
    source-dirs:         app/a07
    ghc-options:
    - -rtsopts

  B07:
    main:                Main.hs
    source-dirs:         app/b07
    ghc-options:
    - -rtsopts

  A08:
    main:                Main.hs
    source-dirs:         app/a08
    ghc-options:
    - -rtsopts

  B08:
    main:                Main.hs
    source-dirs:         app/b08
    ghc-options:
    - -rtsopts

  A09:
    main:                Main.hs
    source-dirs:         app/a09
    ghc-options:
    - -rtsopts
  
  B09:
    main:                Main.hs
    source-dirs:         app/b09
    ghc-options:
    - -rtsopts
 
  A10:
    main:                Main.hs
    source-dirs:         app/a10
    ghc-options:
    - -rtsopts

  A11:
    main:                Main.hs
    source-dirs:         app/a11
    ghc-options:
    - -rtsopts

  B11:
    main:                Main.hs
    source-dirs:         app/b11
    ghc-options:
    - -rtsopts

  A12:
    main:                Main.hs
    source-dirs:         app/a12
    ghc-options:
    - -rtsopts

  B12:
    main:                Main.hs
    source-dirs:         app/b12
    ghc-options:
    - -rtsopts

  A13:
    main:                Main.hs
    source-dirs:         app/a13
    ghc-options:
    - -rtsopts

  B13:
    main:                Main.hs
    source-dirs:         app/b13
    ghc-options:
    - -rtsopts

  A14:
    main:                Main.hs
    source-dirs:         app/a14
    ghc-options:
    - -rtsopts

  B14:
    main:                Main.hs
    source-dirs:         app/b14
    ghc-options:
    - -rtsopts

  A15:
    main:                Main.hs
    source-dirs:         app/a15
    ghc-options:
    - -rtsopts

  A16:
    main:                Main.hs
    source-dirs:         app/a16
    ghc-options:
    - -rtsopts

  B16:
    main:                Main.hs
    source-dirs:         app/b16
    ghc-options:
    - -rtsopts

tests:
  tessoku-book-test:
    main:                spec.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - tessoku-book
    - hspec
    - main-tester

  tessoku-book-doctest:
    main:                doctests.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - tessoku-book
    - doctest
