name:                tessoku-book
version:             0.1.0.0
github:              "nobsun/tessoku-book"
license:             BSD3
author:              "Nobuo Yamashita"
maintainer:          "nobsun@sampou.org"
copyright:           "Copyright: (c) 2022 Nobuo Yamashita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/tessoku-book#readme>

dependencies:
- base >= 4.7 && < 5
- unicode-show
- bytestring
- utf8-string
- time
- hspec
- array

library:
  source-dirs: src

executables:
  tessoku-book:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    # - -threaded
    # - -with-rtsopts=-N
    dependencies:
    - tessoku-book
  
  A01:
    main:                Main.hs
    source-dirs:         app/a01

  B01:
    main:                Main.hs
    source-dirs:         app/b01
  
  A02:
    main:                Main.hs
    source-dirs:         app/a02

  B02:
    main:                Main.hs
    source-dirs:         app/b02

  A03:
    main:                Main.hs
    source-dirs:         app/a03

  B03:
    main:                Main.hs
    source-dirs:         app/b03

  A04:
    main:                Main.hs
    source-dirs:         app/a04

  B04:
    main:                Main.hs
    source-dirs:         app/b04

  A05:
    main:                Main.hs
    source-dirs:         app/a05

  A06:
    main:                Main.hs
    source-dirs:         app/a06

  B06:
    main:                Main.hs
    source-dirs:         app/b06

  A07:
    main:                Main.hs
    source-dirs:         app/a07

tests:
  tessoku-book-test:
    main:                spec.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - tessoku-book
    - hspec
    - main-tester

  tessoku-book-doctest:
    main:                doctests.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - tessoku-book
    - doctest
